In [4]:
import random
import csv

# Generating synthetic historical prices gradually increasing from 150 to 180 with occasional falls
historical_prices = []
current_price = 57.4
for _ in range(80):
    
    current_price += random.uniform(-0.6, 1.2)
    current_price = max(min(current_price, 70.4), 57)   # Ensure prices stay within 48 to 52 range
    historical_prices.append(current_price)


# Synthetic dataset generation
dataset = []

c = 0
for price in historical_prices[:-1]:
    
    error = random.uniform(0, 0.04)
    expected_value = historical_prices[c + 1] + ((historical_prices[c + 1] - price) * error * random.choice([-1,1]))
    error = error*price
    percentage_portfolio = random.uniform(0.5, 5.0)
    percentage_sector = random.uniform(5.0, 20.0)
    sector = 'IT'
    action = ""
    if random.random() > 0.8:
        action = random.choice(['Buy', 'Sell', 'Keep'])
    else:
        if ((expected_value - price) > error):
            action = 'Buy'
        elif ((price - expected_value) > error):
            action = 'Sell'
        else:
            action = 'Keep'

    row = [price, expected_value, error, percentage_portfolio, percentage_sector, sector, action]
    dataset.append(row)
    c += 1
print(dataset)
# Writing the dataset to a CSV file
with open('tgt_stock_trades.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Current Value of Stock', 'Expected Value of Stock', 'Error in expected value of stock',
                     'Percentage of portfolio', 'Percentage of sector', 'Sector of stock', 'Buy/Sell/Keep'])
    writer.writerows(dataset)

print("Dataset generated and saved to apple_stock_trades.csv")


[[57.46791568800821, 57.252377830691536, 0.25979245172919985, 2.0033644221949984, 19.051375307843394, 'IT', 'Keep'], [57.25139903423353, 57.837462043750705, 0.9679649937051007, 0.9582901414725769, 5.982952632531975, 'IT', 'Keep'], [57.82771806102623, 57.77351476155054, 2.1943240924691594, 1.5166626154681278, 14.104914282543223, 'IT', 'Sell'], [57.77137684406166, 58.015544212122954, 1.7588271699410654, 3.438796827380142, 7.0550818001134346, 'IT', 'Keep'], [58.0083302573235, 58.15541048059756, 2.2115461844559965, 1.319215789081291, 15.566989036510954, 'IT', 'Keep'], [58.16124011239437, 57.62820243869759, 0.6862842144032943, 1.1371397657134692, 11.100764727271365, 'IT', 'Keep'], [57.621837660588156, 57.03482183857489, 2.2057104624001704, 0.5435477820064997, 19.2924504175281, 'IT', 'Keep'], [57.056463824262615, 57.74204324792388, 0.7679692581769699, 0.8234147302197693, 13.247732484583537, 'IT', 'Keep'], [57.73293803247525, 58.39408959285691, 0.4109461603159185, 4.001703477836102, 17.438243

In [5]:
import pandas as pd

In [6]:
df_tgt = pd.read_csv('./tgt_stock_trades.csv')
df_tgt['Sector of stock'] = 'Consumer Discretionary'

df_pzr = pd.read_csv('./tgt_stock_trades.csv')
df_pzr['Sector of stock'] = 'Health Care'

df_jnpr = pd.read_csv('./jnpr_stock_trades.csv')
df_jnpr['Sector of stock'] = 'Telecommunications'

df_jnj = pd.read_csv('./jnj_stock_trades.csv')
df_jnj['Sector of stock'] = 'Health Care'

In [7]:

df_decisions = []
df_decisions.append(pd.read_csv('./amazon_stock_trades.csv'))
df_decisions.append(pd.read_csv('./apple_stock_trades.csv'))
df_decisions.append(pd.read_csv('./cisco_stock_trades.csv'))
df_decisions.append(pd.read_csv('./ibm_stock_trades.csv'))
df_decisions.append(df_jnj)
df_decisions.append(df_jnpr)
df_decisions.append(pd.read_csv('./orcl_stock_trades.csv'))
df_decisions.append(df_pzr)
df_decisions.append(df_tgt)
df_decisions.append(pd.read_csv('./msft_stock_trades.csv'))


In [150]:
df_senti_stock = pd.read_csv('./Combining Stock and Twitter Data/MyDrive/PfizerStock_Sentiment_6M.csv')
df_senti_stock

date   open    low   high    volume  close Name       Date  \
0    10/2/2017  35.67  35.49  36.10  15287990  36.07  PFE  10/2/2017   
1    10/3/2017  36.02  35.75  36.20  13528203  36.14  PFE  10/3/2017   
2    10/4/2017  36.18  35.90  36.24  10815755  35.96  PFE  10/4/2017   
3    10/5/2017  35.88  35.75  36.00  13060859  36.00  PFE  10/5/2017   
4    10/6/2017  35.99  35.94  36.14  11247289  36.05  PFE  10/6/2017   
..         ...    ...    ...    ...       ...    ...  ...        ...   
104   3/5/2018  35.82  35.77  36.28  21176053  36.12  PFE   3/5/2018   
105   3/6/2018  36.24  35.75  36.24  17077142  35.88  PFE   3/6/2018   
106   3/7/2018  35.60  35.55  36.08  22239404  35.93  PFE   3/7/2018   
107   3/8/2018  35.99  35.93  36.50  19416679  36.50  PFE   3/8/2018   
108   3/9/2018  36.75  36.02  37.30  19761851  37.20  PFE   3/9/2018   

       Positve  Negative    Neutral  Total  NeutralPos  NeutralNeg  
0    29.545455  5.000000  65.454545    220   30.038074    5.000000  
1    26.506024  9.036145  64.457831    166   26.506024    9.540240  
2    22.426471  3.308824  74.264706    272   31.729250    3.308824  
3    28.662420  7.643312  63.694268    157   28.662420    8.910971  
4    28.455285  4.878049  66.666667    123   30.160025    4.878049  
..         ...       ...        ...    ...         ...         ...  
104  26.785714  7.142857  66.071429    168   27.895217    7.142857  
105  30.246914  7.407407  62.345679    162   30.246914   10.023655  
106  24.725275  6.593407  68.681319    182   28.444667    6.593407  
107  24.043716  4.371585  71.584699    183   30.666489    4.371585  
108  24.043716  4.371585  71.584699    183   30.666489    4.371585  

[109 rows x 14 columns]

In [151]:
df_decisions_2 = []

# for amazonn

iterator = df_senti_stock.iterrows()
_, row = next(iterator)
for  index, next_row in iterator:
    temp_df = []
    if(index+1 == df_senti_stock.shape[0]):
            break
    current_price = row['open']
    expected_value = (next_row['open'] + next_row['close'])/2
    error_value = abs(next_row['high'] - next_row['low'])
    percentage_portfolio = random.uniform(0.5, 5.0)
    percentage_sector = random.uniform(5.0, 20.0)
    sector = 'Health'
    action = ""
    if random.random() > 0.8:
        action = random.choice(['Buy', 'Sell', 'Keep'])
    else:
        if ((expected_value - price) > error):
            action = 'Buy'
        elif ((price - expected_value) > error):
            action = 'Sell'
        else:
            action = 'Keep'
    positive = row['Positve']
    negative = row['Negative']
    total = row['Total']
    neutral = row['Neutral']
    neutral_pos = row['NeutralPos']
    neutral_neg = row['NeutralNeg']
    temp_df = [current_price, expected_value, error_value, percentage_portfolio, percentage_sector, sector, action, positive, negative, total, neutral, neutral_pos, neutral_neg]
    df_decisions_2.append(temp_df)
    
    row = next_row
print(len(df_decisions_2))
    
with open('pfizer_stock_trades.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Current Value of Stock', 'Expected Value of Stock', 'Error in expected value of stock', 'Percentage of portfolio', 'Percentage of sector', 'Sector of stock', 'Buy/Sell/Keep', 'Positive', 'Negative', 'Neutral', 'Total' , 'Neutral_Pos', 'Neutral_Neg'])
    writer.writerows(df_decisions_2)
    
    

107


In [152]:
df_decisions = []
df_decisions.append(pd.read_csv('./amazon_stock_trades.csv'))
df_decisions.append(pd.read_csv('./apple_stock_trades.csv'))
df_decisions.append(pd.read_csv('./cisco_stock_trades.csv'))
df_decisions.append(pd.read_csv('./ibm_stock_trades.csv'))
df_decisions.append(pd.read_csv('./jnj_stock_trades.csv'))
df_decisions.append(pd.read_csv('./jnpr_stock_trades.csv'))
df_decisions.append(pd.read_csv('./orcl_stock_trades.csv'))
df_decisions.append(pd.read_csv('./pfizer_stock_trades.csv'))
df_decisions.append(pd.read_csv('./tgt_stock_trades.csv'))
df_decisions.append(pd.read_csv('./msft_stock_trades.csv'))

In [153]:
df_decisions[9]

Current Value of Stock  Expected Value of Stock  \
0                     74.71                   74.465   
1                     74.67                   74.345   
2                     74.00                   75.595   
3                     75.22                   75.835   
4                     75.67                   76.130   
..                      ...                      ...   
102                   93.99                   92.315   
103                   91.58                   92.990   
104                   92.34                   93.830   
105                   94.34                   93.510   
106                   93.16                   94.350   

     Error in expected value of stock  Percentage of portfolio  \
0                              0.6850                 2.293516   
1                              1.0100                 0.712645   
2                              1.1600                 2.397191   
3                              0.4900                 4.083279   
4                              0.6900                 1.789788   
..                                ...                      ...   
102                            2.2900                 3.191280   
103                            2.0100                 2.774035   
104                            1.5490                 1.830728   
105                            1.5106                 2.036057   
106                            1.3350                 2.825061   

     Percentage of sector Sector of stock Buy/Sell/Keep   Positive   Negative  \
0                8.124612              IT           Buy  36.962366  11.962366   
1               18.539154              IT           Buy  39.889197  10.387812   
2                8.822657              IT           Buy  40.843023   9.883721   
3                7.400816              IT           Buy  42.518939   8.049242   
4               19.917747              IT           Buy  41.783217   9.965035   
..                    ...             ...           ...        ...        ...   
102             14.987617              IT           Buy  44.366197   8.098592   
103             11.042822              IT           Buy  44.955752  11.327434   
104              8.311487              IT           Buy  39.398998  12.520868   
105             12.908385              IT           Buy  38.803681  10.122699   
106             14.631528              IT           Buy  46.561605  11.318052   

     Neutral      Total  Neutral_Pos  Neutral_Neg  
0        744  51.075269    40.825048    11.962366  
1        722  49.722992    42.399602    10.387812  
2        688  49.273256    42.903692     9.883721  
3       1056  49.431818    44.738171     8.049242  
4        572  48.251748    42.822378     9.965035  
..       ...        ...          ...          ...  
102      568  47.535211    44.688822     8.098592  
103      565  43.716814    44.955752    14.823206  
104      599  48.080134    40.266545    12.520868  
105      652  51.073620    42.664714    10.122699  
106      698  42.120344    46.561605    16.410295  

[107 rows x 13 columns]

In [154]:
import numpy as np

In [155]:
dataset = []
for i in df_decisions:
    dataset.append(i.values)
dataset = np.concatenate(dataset, axis = 0)
print(dataset)

[[964.0 957.55 13.32000000000005 ... 55.33399801 37.0887338 14.26021879]
 [958.0 959.83 13.740000000000007 ... 50.75414781 38.15987934 22.34877364]
 [954.21 975.425 11.870000000000005 ... 53.10344828 36.16858238
  19.64146967]
 ...
 [92.34 93.83 1.5489999999999924 ... 48.08013356 40.26654512 12.52086811]
 [94.34 93.51 1.5105999999999966 ... 51.07361963 42.66471384 10.12269939]
 [93.16 94.35 1.3349999999999935 ... 42.12034384 46.56160458 16.41029451]]


In [124]:
with open('stock_decisions.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Current Value of Stock', 'Expected Value of Stock', 'Error in expected value of stock', 'Percentage of portfolio', 'Percentage of sector', 'Sector of stock', 'Buy/Sell/Keep', 'Positive', 'Negative', 'Neutral', 'Total', 'Neutral_Pos', 'Neutral_Neg'])
    writer.writerows(dataset)